apiVersion: apps/v1

kind: Deployment # configuration type
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: # specification of the deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: # specification for the pod
    metadata:
      labels:
        app: nginx
    spec: # specs of this container
      containers:
        - name: nginx
          image: nginx:1.21.3
          ports:
            - containerPort: 8080